name: version-migration
description: This repository is for trying version migration

branding:
  icon: airplay
  color: green
    
configs:
  repo-metadata:
    parameters:
      description: 'A react-app template'
      topics:
        - react-app
        - nodejs
init:
  uses: stack-init.yml
